global using System.ComponentModel;
global using System.Diagnostics;
global using System.Globalization;
global using System.Net;
global using System.Net.NetworkInformation;
global using System.Net.Sockets;
global using System.Reflection;
global using System.Runtime.CompilerServices;
global using System.Runtime.InteropServices;
global using System.Text;
global using System.Text.RegularExpressions;
global using Microsoft.Extensions.Logging;
global using RaspberryPi;
global using RaspberryPi.Extensions;
global using RaspberryPi.Internals;
global using RaspberryPi.Internals.ResourceLoader;
global using RaspberryPi.Internals.ResourceLoader.Exceptions;
global using RaspberryPi.Network;
global using RaspberryPi.Process;
global using RaspberryPi.Services;
global using RaspberryPi.Storage;
global using RaspberryPi.Utils;
global using UnitsNet;
global using Directory = RaspberryPi.Storage.Directory;
global using File = RaspberryPi.Storage.File;
global using SystemNetworkInterface = System.Net.NetworkInformation.NetworkInterface;
global using SystemProcess = System.Diagnostics.Process;